apiVersion: v1
kind: Service
metadata:
  name: deis-workflow
  labels:
    heritage: deis
    routable: "true"
  annotations:
    router.deis.io/domains: deis
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    name: deis-workflow
